kind: Pod
apiVersion: v1
metadata:
  name: multi-container
  namespace: expense
spec:
 containers:
 - name: nginx
   image: nginx:stable-perl
 - name: nginx
   image: almalinux:9
   command: ["sleep","1000"]
